.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH vagalume 1 "2009\-02\-10"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
vagalume \- GTK+\-based client for the Last.fm online radio service
.SH SYNOPSIS
.B vagalume
.I [OPTIONS] [URL]
.SH DESCRIPTION
This manual page documents briefly the
.B vagalume
command.
.PP
.B Vagalume
is a Last.fm client designed for the Gnome desktop environment. It's
small and provides the basic Last.fm features, such as scrobbling,
tags, recommendations, etc. Vagalume is also designed to work in the
Maemo platform, used by some Nokia devices such as the Nokia 770, N800
and N810

.SH OPTIONS
.TP
.B \-h
Display a brief summary of the command\-line options and their default
values.
.TP
.BI \-c "\| converter\^"
GStreamer converter (or 'none' to disable it)
.TP
.BI \-d "\| decoder\^"
GStreamer decoder
.TP
.BI \-s "\| sink\^"
GStreamer sink
.TP
.BI \-m "\| mixer\^"
GStreamer mixer (if Vagalume was compiled with mixer support)
.TP
.B URL
A Last.fm radio address, beginning with
.I lastfm://
.SH FILES
.TP
.I ~/.vagalume/config.xml
Vagalume config file.
.TP
.I ~/.vagalume/bookmarks.xml
Vagalume bookmarks file.
.SH SEE ALSO
.BR vagalumectl (1)
.SH AUTHOR
This manpage has been written by
Alberto Garcia <agarcia@igalia.com>
